version: "3.8"

services:
  app:
    build: .
    container_name: event_booking_app
    ports:
      - "5000:5000"   # host:container
    env_file:
      - .env          # load environment variables
    volumes:
      - .:/app        # mount local code for live reload in dev
    restart: unless-stopped
